#!/bin/bash

servicename=testapp

watchdog() {
  while(true); do
    FAIL=0

    for pid in $(pgrep $servicename); do
      if [[ $(ps -o state= -p "$pid") = T ]]; then
        FAIL=1;
      fi
    done

    if [[ $FAIL -eq 0 ]]; then
      /bin/systemd-notify WATCHDOG=1;
      sleep 1
    else
      sleep 2;
    fi
  done
}

watchdog &
